services:
  backend:
    build:
      context: ./whisper_turbo_selfhosted/backend
    ports:
      - 8001:8001
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 
              capabilities: [gpu]
  frontend:
    build:
      context: ./whisper_turbo_selfhosted/frontend/whisper-realtime-frontend
    ports:
      - 80:80
  rmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # RabbitMQ messaging port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: demo-user
      RABBITMQ_DEFAULT_PASS: demo-pwd
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
      